### PR TITLE
grin-rfc: update to latest commit

### PR DESCRIPTION
**Pull request by raballew**
Update the submodule to latest commit upstream so that most of the broken links are fixed.

### CODE REVIEW

**Comment by Paouky** [comment]
@quentinlesceller I'm not sure what this does, can you have a look

**Comment by raballew** [comment]
@Paouky I updated the git submodule reference to the latest version of the grin-rfc repository as the currently referenced version contains a lot of broken links.

**Comment by quentinlesceller** [comment]
Nice @raballew. Thank you for that. Indeed that was a very old commit ! LGTM.

**Comment by raballew** [comment]
@quentinlesceller I would suggest that both grin-rfc and grin-docs are safeguarded by some CI checks before merging.

**Comment by quentinlesceller** [comment]
Can you enable the ci workflow on PR as well?

**Comment by raballew** [comment]
@quentinlesceller I can modify the github action but can not enforce the setting in the repository. That has to be done by someone with proper permissions.

**Comment by quentinlesceller** [comment]
AFAIK You don't need specific permissions. Just add a test file with:
```yml
# Trigger the workflow on push or pull request
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'
```

Once merged this will trigger the test on push and PR.

**Pull request merged**
