### PR TITLE
optimize images by about 40%

### PR DESCRIPTION
**Pull request by Th0rgal**
Hey there,

This PR optimizes the images of the docs by about 40%, thanks to @Paouky for the suggestion.

Sincerely,
Thomas

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Can you show a before/after example? Is the quality downgrade noticeable ?

**Comment by Th0rgal** [comment]
> Can you show a before/after example? Is the quality downgrade noticeable ?

For sure:
Optimized: https://github.com/Th0rgal/docs/blob/62250ad8dd27818cfded8261d8c604104d238e38/docs/assets/images/receiver-msg.png
Default: 
https://github.com/Th0rgal/docs/blob/9ea8fcf69142d97e3bb480848c3057dcf601bf7b/docs/assets/images/receiver-msg_prev.png

You can directly check this folder: https://github.com/Th0rgal/docs/tree/62250ad8dd27818cfded8261d8c604104d238e38/docs/assets/images
and this one (unoptimized):
https://github.com/Th0rgal/docs/tree/9ea8fcf69142d97e3bb480848c3057dcf601bf7b/docs/assets/images

As a human I am not able to see the difference but I believe this is not lossless. I used the imgbot tool which is using ImageMagick (http://www.imagemagick.org/), Svgo (https://github.com/svg/svgo) and MozJpeg (https://github.com/mozilla/mozjpeg).

**Comment by quentinlesceller** [comment]
Indeed I cannot see any difference... @Paouky what do you think?

**Comment by Paouky** [comment]
@quentinlesceller This is great. @Th0rgal already made these kind of adjustments a couple weeks back and I was also skeptical at first, but there no issues afterwards and images look good. 

Thank you for the PR!

**Comment by quentinlesceller** [comment]
Okay LGTM :)

**Pull request merged**
