### PR TITLE
Fix multiple grammatical errors

### PR DESCRIPTION
**Pull request by raballew**
Fixed some more typos.

### CODE REVIEW

**Comment by raballew** [comment]
It seems that the docs, despite having a good top level structure and providing useful insights in the relevant parts of `mimblewimble`, lack a [common coding style](https://google.github.io/styleguide/docguide/style.html) as show here for example. Also some links seem to be outdated. This could be tracked in a separate PR or issue.

**Review by quentinlesceller — APPROVED** [review]
Good catch again @raballew. Feel free to send open several PRs 😄.

**Comment by raballew** [comment]
@quentinlesceller Sure, I will do exactly this the comming days when I continue reading through the docs. I could not find a contributing guide for the docs repository. Anything I should be aware of before starting?

**Comment by quentinlesceller** [comment]
We do have a contributing guide for the main repo https://github.com/mimblewimble/grin/blob/master/CONTRIBUTING.md but I don't that's applicable to our situation here. For now, no special thing to say.

**Comment by Paouky** [comment]
Appreciate the willingness to help, @raballew. Not following a style guide was a rookie mistake on my part.

**Pull request merged**
